print("Hola mi nombre es: Luis")
print("Tengo 39 años de edad")
print("Estudio en el ISB")
print("Yo quiero estudiar Ciencia de datos")
print("Estoy en Área 1 por: ")
print("Espero poder crear con python: ")
print("A la universidad que quiero entrar es: ")
print("Me gusta la programación por:")
print("Mi libro favorito es:La divina comedia")
print("Mi comida favorita es: ")
print("pienso que las matemáticas son: ")
